baseURL = "https://blog.ryotak.me/"
languageCode = "ja-jp"
title = "RyotaK's Blog"
theme = "anatole"

[params]
title = "RyotaK's Blog"
author = "RyotaK"
description = "Hello!"
profilePicture = "images/profile.jpg"

[[params.socialIcons]]
icon = "fa-twitter"
title = "Twitter"
url = "https://twitter.com/ryotkak"

[[params.socialIcons]]
icon = "fa-github"
title = "GitHub"
url = "https://github.com/Ry0taK"
